### ISSUE TITLE
UDHR for Cherokee

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/nototools#239]
Please add

  http://unicode.org/udhr/d/udhr_chr.html

to the nototools repository.

**Comment by dougfelt** [comment]
The repository contains the full xml files, and udhr_chr.xml is already there.

The sample_texts directory does not contain the article 1 text for Cherokee because the tooling ignores udhr files under stage 3 (as listed in the index).  In this case, the article 1 text is the only part of the sample text that was translated, so the Cherokee data is at stage 1.  This means 'no known complete translation', while stage 3 means 'partially converted to unicode' (with a note that partial translations often only include the first article). UDHR chose to use stage 1 instead of stage 3 for this.   As is obvious, these categories don't form a clean partition, you could label the sample with both if these were flags and not 'stages'.

I'll manually add this sample but probably won't change the tooling to deal with this.

**Comment by lemzwerg** [comment]
Thanks for the quick fix!
