### ISSUE TITLE
noto_lint.py:  please teach noto_lint about NotoSansArabic.

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#336]
noto_lint doesn't know about NotoSansArabic and how its names should work.  please teach noto_lint about it.

**Comment by marekjez86** [comment]
same applies to NotoSansArabicUI and NotoSansHebrew (I haven't checked yet about NotoSerifHebrew)

**Comment by marekjez86** [comment]
same for NotoSansKhmer (I suspect also for NotoSerifKhmer)

**Comment by dougfelt** [comment]
@marekjez86 I don't understand what your issue is w.r.t. Hebrew and Khmer.  Unlike with Arabic, noto_lint does have name data for these.  What exactly is the problem you're having with Hebrew and Khmer?

**Comment by marekjez86** [comment]
For example for NotoSansKhmer I get:

Automatic testing for 'NotoSansKhmer-Thin.ttf', Version 1.901:
E <name/unable_to_check> No name data available for this font.

How do I resolve the above problem?
================================
Automatic testing for 'NotoSansHebrew-Thin.ttf', Version 1.902:
E <name/unable_to_check> No name data available for this font.

How do I resolve the above problem?

I though we need to "teach" noto_lint about NotoSansHebrew, NotoSansKhmer ... to resolve it but if there's some other way I'll be glad to work on fixing these errors.

**Comment by dougfelt** [comment]
That's odd.  My repo has a change to these but I don't see how it got there, and it's not in the public repo.  My mistake.

The expected names was built originally from the phase 3 planning spreadsheet scope tab.  There we refer to these fonts as 'Arabic Sans New', 'Hebrew Sans New' and a bunch of others with '(new?)' because we never decided what they should be named, so just punted.

Now of course fonts are being delivered with whatever names someone most recently decided to use and lint has no idea.  This means, basically, that as new scripts are delivered lint will trip over this and need to be updated to deal with each late-breaking change.

Can you go over that list and determine what the names should be for the fonts we never quite made a decision on?

**Comment by marekjez86** [comment]
You are right. That (* New) was the decision re new names. Thank you for the reminder. I'll go over the list. Taking bug ownership for now.
