### ISSUE TITLE
unicode_data as a separate package?

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/nototools#460]
How about we make the very useful `nototools.unicode_data` module into a separate distribution package that one could pip-install without needing to pull in the whole nototools?

The import name could be simply "ucd" (I checked PyPI, I doesn't have one named like that). Just "unicode_data" may look like a misspelling of the built-in `unicodedata`.
The repository could be named "python-ucd" or "py-ucd", and it would be hosted under the googlei18n github organization.

The nototools package would still be able to load from its "beeding-edge" data files by providing a custom path to `ucd` module. However, I think it would be more useful for the general public that by default the embedded data files were in sync with the currently published Unicode version.

A lot of projects could benefit from this. For example, glyphsLib, defcon or even fonttools:
https://github.com/typesupply/defcon/pull/124

Not only the built-in unicodedata module has different versions for each python version (sure, there's the [backport](https://github.com/mikekap/unicodedata2)), but it also does not expose the whole unicode character data (it's missing scripts, blocks, etc.).

If nototools maintainers are OK with the idea, I could volunteer bootstrapping the new project on Github and deal with the packaging stuff.

/cc @roozbehp @dougfelt @behdad @twardoch and others...

**Comment by dougfelt** [comment]
Might be ok.  While the unicode_data parsing/access to data is good enough for nototools, I'm not sure it's quite up to speed in general.  pyicu wraps icu's access to unicodedata and is probably the canonical way to get the official data.  But pyicu requires icu...

It is a key feature of unicode_data that it uses the prerelease unicode data files.  This is important for nototools because we generate information about scripts/characters/emoji from the prerelease data.  Occasionally new data files require code changes because parsing is a bit different, so just dropping in new data files, while generally ok, is often not quite right. So nototools will have to use its own version anyway.  I suppose it could be forked off an upstream 'py-ucd' so fixes and additions upstream could be merged down into it from time to time.

Anyway I have no particular objections.

**Comment by anthrotype** [comment]
Thanks Doug.

> I'm not sure it's quite up to speed in general

I think it's fine for "offline" font development tools.

> Occasionally new data files require code changes because parsing is a bit different

maybe, instead of a fork, the py-ucd repo could have a development branch where the code changes required to parse those bleeding-edge files could live, and nototools could pull that branch as a git submodule.

**Comment by anthrotype** [comment]
actually, I changed my mind and realized it would be easy enough to rewrite what I needed directly in fonttools
https://github.com/fonttools/fonttools/pull/1106

**Comment by behdad** [comment]
Should we make nototools use the new stuff in fonttools then?  Or just leave as is. Perhaps leave as is.
