### ISSUE TITLE
Does nototools support python3?

### ISSUE THREAD

**Issue by juanitotc** [googlei18n/nototools#463]
After compiling nototools with python3.6, I get a number of errors that seen due to syntax differences between python2 and python3:

  File "/usr/local/lib/python3.6/site-packages/nototools/font_data.py", line 133
    expected_bitmap = 0L
                                     ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/site-packages/nototools/unicode_data.py", line 1110
    print 'already have data for sequence:', seq_to_string(k), t
                                                                 ^
SyntaxError: invalid syntax

**Comment by dougfelt** [comment]
No it does not support python3.

On Oct 28, 2017 4:16 AM, "juanitotc" <notifications@github.com> wrote:

After compiling nototools with python3.6, I get a number of errors that
seen due to syntax differences between python2 and python3:

File "/usr/local/lib/python3.6/site-packages/nototools/font_data.py", line
133
expected_bitmap = 0L
^
SyntaxError: invalid syntax

File "/usr/local/lib/python3.6/site-packages/nototools/unicode_data.py",
line 1110
print 'already have data for sequence:', seq_to_string(k), t
^
SyntaxError: invalid syntax

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/nototools/issues/463>, or mute the thread

**Comment by juanitotc** [comment]
Thanks - it might be worth a mention in the readme?

**Comment by dougfelt** [comment]
Quite right.  I've updated the readme in noto-emoji.
